export const UPDATE_SELECTED_DATE_MONTH_YEAR='UPDATE_SELECTED_DATE_MONTH_YEAR';
export const ADD_EXPENSE='ADD_EXPENSE';
export const ADD_INCOME='ADD_INCOME';
export const DELETE_EXPENSE='DELETE_EXPENSE';
export const DELETE_INCOME='DELETE_INCOME';
export const UPDATE_EXPENSE='UPDATE_EXPENSE';
export const UPDATE_INCOME='UPDATE_INCOME';